cli_wallet_connection: ws://47.94.107.109:38091
registrar_account: nathan
referrer_percent: 50
refcode_prefix: F01

default_url: 0.0.0.0
default_port: 3000

exception_notification:
  sender_address: faucet@example.com
  exception_recipients: admin@example.com

smtp:
  address: address
  user_name: user
  password: password
